# Generated by Django 5.1.5 on 2025-01-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
